import { createAudioPlayer, setAudioModeAsync, type AudioPlayer } from 'expo-audio';

// Master mute, owned here so this lib stays React/Zustand-free. The UI flips
// it through sfxStore (which calls setSfxMuted) — dependency points stores→lib.
let muted = false;
export function setSfxMuted(value: boolean) {
  muted = value;
}

// Chiptune SFX clips (generated by scripts/gen-sfx.js).
const sources = {
  zap: require('../../assets/sfx/zap.wav'),
  detonate: require('../../assets/sfx/detonate.wav'),
  boulder: require('../../assets/sfx/boulder.wav'),
  launch: require('../../assets/sfx/launch.wav'),
  beam: require('../../assets/sfx/beam.wav'),
  laser: require('../../assets/sfx/laser.wav'),
  stun: require('../../assets/sfx/stun.wav'),
  stone: require('../../assets/sfx/stone.wav'),
  morph: require('../../assets/sfx/morph.wav'),
  absorb: require('../../assets/sfx/absorb.wav'),
  powerup: require('../../assets/sfx/powerup.wav'),
  dominate: require('../../assets/sfx/dominate.wav'),
  teleport: require('../../assets/sfx/teleport.wav'),
  capture: require('../../assets/sfx/capture.wav'),
  move: require('../../assets/sfx/move.wav'),
} as const;

export type SfxKey = keyof typeof sources;

// Players are created lazily and reused; replaying seeks to 0 and plays again.
const players: Partial<Record<SfxKey, AudioPlayer>> = {};
let inited = false;

function ensureInit() {
  if (inited) return;
  inited = true;
  // Play even when the device ringer is silenced.
  setAudioModeAsync({ playsInSilentMode: true }).catch(() => {});
}

export function playSfx(key: SfxKey) {
  if (muted) return;
  ensureInit();
  try {
    let p = players[key];
    if (!p) {
      p = createAudioPlayer(sources[key]);
      players[key] = p;
    }
    p.seekTo(0);
    p.play();
  } catch {
    // never let audio errors interrupt gameplay
  }
}

// Maps a GameState effect type → the SFX clip to play. Several effects share
// a clip (king/tower → laser, transform/convert → morph, etc.).
const EFFECT_SFX: Partial<Record<string, SfxKey>> = {
  detonate: 'detonate',
  launch: 'launch',
  boulder: 'boulder',
  beam: 'beam',
  kingShot: 'laser',
  towerShot: 'laser',
  zap: 'zap',
  stun: 'stun',
  stone: 'stone',
  transform: 'morph',
  convert: 'morph',
  howlerAbsorb: 'absorb',
  raise: 'powerup',
  revive: 'powerup',
  dominate: 'dominate',
  swap: 'teleport',
  portalOut: 'teleport',
};

export function playEffectSfx(effectType: string) {
  const key = EFFECT_SFX[effectType];
  if (key) playSfx(key);
}
