import type { PieceType, Color } from '@/types/game';
import { ImageSourcePropType } from 'react-native';

const spriteMap: Record<string, ImageSourcePropType> = {
  WhitePawn: require('../../assets/sprites/WhitePawn.png'),
  WhiteKnight: require('../../assets/sprites/WhiteKnight.png'),
  WhiteBishop: require('../../assets/sprites/WhiteBishop.png'),
  WhiteRook: require('../../assets/sprites/WhiteRook.png'),
  WhiteQueen: require('../../assets/sprites/WhiteQueen.png'),
  WhiteKing: require('../../assets/sprites/WhiteKing.png'),
  WhiteNecroPawn: require('../../assets/sprites/WhiteNecroPawn.png'),
  WhiteGhostKnight: require('../../assets/sprites/WhiteGhostKnight.png'),
  WhiteNecromancer: require('../../assets/sprites/WhiteNecromancer.png'),
  WhiteDeadLauncher: require('../../assets/sprites/WhiteDeadLauncher.png'),
  WhiteGhoulKing: require('../../assets/sprites/WhiteGhoulKing.png'),
  WhiteQueenOfBones: require('../../assets/sprites/WhiteQueenOfBones.png'),
  WhiteHellPawn: require('../../assets/sprites/WhiteHellPawn.png'),
  WhiteProwler: require('../../assets/sprites/WhiteProwler.png'),
  WhiteHowler: require('../../assets/sprites/WhiteHowler.png'),
  WhiteBeholder: require('../../assets/sprites/WhiteBeholder.png'),
  WhiteHellKing: require('../../assets/sprites/WhiteHellKing.png'),
  WhiteQueenOfDestruction: require('../../assets/sprites/WhiteQueenOfDestruction.png'),
  WhitePawnHopper: require('../../assets/sprites/WhitePawnHopper.png'),
  WhiteBeastKnight: require('../../assets/sprites/WhiteBeastKnight.png'),
  WhiteBeastDruid: require('../../assets/sprites/WhiteBeastDruid.png'),
  WhiteBoulderThrower: require('../../assets/sprites/WhiteBoulderThrower.png'),
  WhiteFrogKing: require('../../assets/sprites/WhiteFrogKing.png'),
  WhiteQueenOfDomination: require('../../assets/sprites/WhiteQueenOfDomination.png'),
  WhiteYoungWiz: require('../../assets/sprites/WhiteYoungWiz.png'),
  WhiteFamiliar: require('../../assets/sprites/WhiteFamiliar.png'),
  WhiteWizardTower: require('../../assets/sprites/WhiteWizardTower.png'),
  WhitePortal: require('../../assets/sprites/WhitePortal.png'),
  WhiteWizardKing: require('../../assets/sprites/WhiteWizardKing.png'),
  WhiteQueenOfIllusions: require('../../assets/sprites/WhiteQueenOfIllusions.png'),
  BlackPawn: require('../../assets/sprites/BlackPawn.png'),
  BlackKnight: require('../../assets/sprites/BlackKnight.png'),
  BlackBishop: require('../../assets/sprites/BlackBishop.png'),
  BlackRook: require('../../assets/sprites/BlackRook.png'),
  BlackQueen: require('../../assets/sprites/BlackQueen.png'),
  BlackKing: require('../../assets/sprites/BlackKing.png'),
  BlackNecroPawn: require('../../assets/sprites/BlackNecroPawn.png'),
  BlackGhostKnight: require('../../assets/sprites/BlackGhostKnight.png'),
  BlackNecromancer: require('../../assets/sprites/BlackNecromancer.png'),
  BlackDeadLauncher: require('../../assets/sprites/BlackDeadLauncher.png'),
  BlackGhoulKing: require('../../assets/sprites/BlackGhoulKing.png'),
  BlackQueenOfBones: require('../../assets/sprites/BlackQueenOfBones.png'),
  BlackHellPawn: require('../../assets/sprites/BlackHellPawn.png'),
  BlackProwler: require('../../assets/sprites/BlackProwler.png'),
  BlackHowler: require('../../assets/sprites/BlackHowler.png'),
  BlackBeholder: require('../../assets/sprites/BlackBeholder.png'),
  BlackHellKing: require('../../assets/sprites/BlackHellKing.png'),
  BlackQueenOfDestruction: require('../../assets/sprites/BlackQueenOfDestruction.png'),
  BlackPawnHopper: require('../../assets/sprites/BlackPawnHopper.png'),
  BlackBeastKnight: require('../../assets/sprites/BlackBeastKnight.png'),
  BlackBeastDruid: require('../../assets/sprites/BlackBeastDruid.png'),
  BlackBoulderThrower: require('../../assets/sprites/BlackBoulderThrower.png'),
  BlackFrogKing: require('../../assets/sprites/BlackFrogKing.png'),
  BlackQueenOfDomination: require('../../assets/sprites/BlackQueenOfDomination.png'),
  BlackYoungWiz: require('../../assets/sprites/BlackYoungWiz.png'),
  BlackFamiliar: require('../../assets/sprites/BlackFamiliar.png'),
  BlackWizardTower: require('../../assets/sprites/BlackWizardTower.png'),
  BlackPortal: require('../../assets/sprites/BlackPortal.png'),
  BlackWizardKing: require('../../assets/sprites/BlackWizardKing.png'),
  BlackQueenOfIllusions: require('../../assets/sprites/BlackQueenOfIllusions.png'),
};

export function getSprite(color: Color, type: PieceType): ImageSourcePropType | null {
  return spriteMap[`${color}${type}`] ?? null;
}
